In [1]:
import torch

x = torch.rand(5, 3)
print(x)
print(x.dtype)

tensor([[0.7618, 0.1170, 0.9586],
        [0.4291, 0.0833, 0.3471],
        [0.0482, 0.0894, 0.6838],
        [0.4523, 0.5989, 0.5906],
        [0.0298, 0.7136, 0.0964]])
torch.float32


In [2]:
x = torch.rand(5, 3)
print(x)
print(x.dtype)

tensor([[0.6785, 0.2749, 0.4026],
        [0.2875, 0.2267, 0.9449],
        [0.2114, 0.5248, 0.5510],
        [0.9150, 0.3186, 0.5137],
        [0.8490, 0.5149, 0.1431]])
torch.float32


In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
import numpy as np

data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7858, 0.0142],
        [0.3975, 0.4224]]) 



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6304, 0.3430, 0.0628],
        [0.0632, 0.8840, 0.3445]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)
tensor = torch.ones(3,4, dtype=torch.int16)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.int16
Device tensor is stored on: cpu


In [8]:
# We can move our tensor to the GPU if available
if torch.cuda.is_available():
    print("GPU available")
    tensor = tensor.to("cuda")
else:
    print("GPU not available")  

GPU not available


In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
# Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.
# See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [12]:
# Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [13]:
# In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [2]:
import torch

# Create a tensor from a Python list
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print("Tensor 1:")
print(tensor1)

# Create a tensor from a NumPy array
import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor(numpy_array)
print("\nTensor 2:")
print(tensor2)

# Create a tensor with specific dimensions filled with zeros
tensor3 = torch.zeros(2, 3)
print("\nTensor 3:")
print(tensor3)

# Create a tensor with random values
tensor4 = torch.randn(3, 2)
print("\nTensor 4:")
print(tensor4)


Tensor 1:
tensor([1, 2, 3, 4, 5])

Tensor 2:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor 3:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor 4:
tensor([[-2.0136, -0.2182],
        [-0.0496, -0.5210],
        [ 0.9576, -0.0076]])
