#### Tensors

# Tensors are multi-dimensional arrays that can store numerical data. They are the primary data structure in PyTorch and are used for computations in neural networks.


In [1]:
import torch
import math
import numpy as np

In [2]:
# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
z = torch.zeros(5, 3) # 5x3 tensor with zeros
print(z)
print(z.dtype) # default data type is float32

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [4]:
i = torch.ones((5, 3), dtype=torch.int16) # 5x3 tensor with ones, and data type is int16(integer 16 bits)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


### When working with random numbers in machine learning or other applications, it is often important to have reproducible results. By setting a seed, you can ensure that the sequence of random numbers generated will be the same every time you run your code, which can be useful for debugging or comparing different runs of an experiment.


In [5]:
torch.manual_seed(1729) # seed for random number generator
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [6]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2 # every element is multiplied by 2
print(twos)

threes = ones + twos       # addition allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
# uncomment this line to get a runtime error
# r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


### Here’s a small sample of the mathematical operations available:


In [7]:
r = (torch.rand(2, 2) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) # clamp values to a range

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

A random matrix, r:
tensor([[ 0.9956, -0.2232],
        [ 0.3858, -0.6593]])

Absolute value of r:
tensor([[0.9956, 0.2232],
        [0.3858, 0.6593]])

Inverse sine of r:
tensor([[ 1.4775, -0.2251],
        [ 0.3961, -0.7199]])

Determinant of r:
tensor(-0.5703)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.8353, -0.5497],
        [-0.5497,  0.8353]]),
S=tensor([1.1793, 0.4836]),
V=tensor([[-0.8851, -0.4654],
        [ 0.4654, -0.8851]]))

Average and standard deviation of r:
(tensor(0.7217), tensor(0.1247))

Maximum value of r:
tensor(0.9956)
Common functions:
tensor([[0.7231, 0.0482, 0.4961, 0.9278],
        [0.0124, 0.6939, 0.4823, 0.4587]])
tensor([[-0., -0., 1., -0.],
        [1., 1., -0., -0.]])
tensor([[-1., -1.,  0., -1.],
        [ 0.,  0., -1., -1.]])
tensor([[-0.5000, -0.0482,  0.4961, -0.5000],
        [ 0.0124,  0.5000, -0.4823, -0.4587]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tenso

/var/folders/t2/lz6cdn7s5dbf6m4_78hwndn00000gn/T/ipykernel_77438/2021271175.py:70: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1712608635429/work/aten/src/ATen/native/Cross.cpp:66.)
  print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)


## Shapes


In [8]:
x = torch.empty(2, 2, 3) # uninitialized tensor, reserves memory but does not initialize values
print(x.shape) # 2x2x3 tensor
print(x) 

empty_like_x = torch.empty_like(x) # uninitialized tensor with the same shape as x
print(empty_like_x.shape) # 2x2x3 tensor
print(empty_like_x)

zeros_like_x = torch.zeros_like(x) # tensor with zeros and the same shape as x
print(zeros_like_x.shape) # 2x2x3 tensor
print(zeros_like_x)

ones_like_x = torch.ones_like(x) # tensor with ones and the same shape as x
print(ones_like_x.shape) # 2x2x3 tensor
print(ones_like_x)

rand_like_x = torch.rand_like(x) # tensor with random values and the same shape as x
print(rand_like_x.shape) # 2x2x3 tensor
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.9451, 0.2359, 0.1979],
         [0.3327, 0.6146, 0.5999]],

        [[0.5013, 0.9397, 0.8656],
         [0.5207, 0.6865, 0.3614]]])


## Specify its data directly from a PyTorch collection:


In [9]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]]) # tensor with specific values
print(some_constants) # 2x2 tensor

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19)) 
print(some_integers) # 1D tensor

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9])) 
print(more_integers) # 2x3 tensor


tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


# Data Types

### Setting the datatype of a tensor is possible a couple of ways:


In [10]:
a = torch.ones((2, 3), dtype=torch.int16) # 2x3 tensor with ones, and data type is int16(integer 16 bits)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20. # 2x3 tensor with random values between 0 and 20, and data type is float64(double precision)
print(b)

c = b.to(torch.int32) # convert b to int32(integer 32 bits)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 3.8937, 16.1945, 12.3902],
        [15.0541, 16.8179, 17.7174]], dtype=torch.float64)
tensor([[ 3, 16, 12],
        [15, 16, 17]], dtype=torch.int32)


# Math with tensors


In [11]:
ones = torch.zeros(2, 2) + 1  # 2x2 tensor with ones

twos = torch.ones(2, 2) * 2   # 2x2 tensor with twos

threes = (torch.ones(2, 2) * 7 - 1) / 2  # 2x2 tensor with threes

fours = twos ** 2 # element-wise squaring

sqrt2s = twos ** 0.5 # element-wise square root

powers2 = twos ** torch.tensor([[1, 2], [3, 4]]) # element-wise exponentiation

fives = ones + fours # element-wise addition

dozens = threes * fours # element-wise multiplication

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)
print(powers2)
print(fives)
print(dozens)




tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


### The exception to the same-shapes rule is tensor broadcasting.

#### Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. In the example below, the one-row, four-column tensor is multiplied by both rows of the two-row, four-column tensor.


In [12]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2138, 0.5395, 0.3686, 0.4007],
        [0.7220, 0.8217, 0.2612, 0.7375]])
tensor([[0.4276, 1.0791, 0.7371, 0.8014],
        [1.4439, 1.6434, 0.5224, 1.4750]])


## Altering Tensors in Place

#### Most binary operations on tensors will return a third, new tensor. When we say c = a \* b (where a and b are tensors), the new tensor c will occupy a region of memory distinct from the other tensors.


### Most of the math functions have a version with an appended underscore (\_) that will alter a tensor in place.


In [13]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore, this operation modifies b in place
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


For arithmetic operations, there are functions that behave similarly:


In [14]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8328, 0.8444],
        [0.2941, 0.3788]])

After adding:
tensor([[1.8328, 1.8444],
        [1.2941, 1.3788]])
tensor([[1.8328, 1.8444],
        [1.2941, 1.3788]])
tensor([[0.8328, 0.8444],
        [0.2941, 0.3788]])

After multiplying
tensor([[0.6936, 0.7130],
        [0.0865, 0.1435]])
tensor([[0.6936, 0.7130],
        [0.0865, 0.1435]])


##### There is another option for placing the result of a computation in an existing, allocated tensor. Many of the methods and functions we’ve seen so far - including creation methods! - have an out argument that lets you specify a tensor to receive the output. If the out tensor is the correct shape and dtype, this can happen without a new memory allocation:


In [15]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0929, 0.0261],
        [0.4759, 0.3034]])
tensor([[0.9883, 0.4762],
        [0.7242, 0.0776]])


## Copying Tensors


In [16]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


### But what if you want a separate copy of the data to work on? The clone() method is there for you:


In [17]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

# Turn on autograd
a = torch.rand(2, 2, requires_grad=True) # turn on autograd => computation history tracking is turned on.
print(a)

b = a.clone()
print(b)

c = a.detach().clone() # detach => computation history tracking is turned off. The detach() method detaches the tensor from its computation history
print(c)

print(a)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4004, 0.9877],
        [0.0352, 0.0905]], requires_grad=True)
tensor([[0.4004, 0.9877],
        [0.0352, 0.0905]], grad_fn=<CloneBackward0>)
tensor([[0.4004, 0.9877],
        [0.0352, 0.0905]])
tensor([[0.4004, 0.9877],
        [0.0352, 0.0905]], requires_grad=True)


## Manipulating Tensor Shapes

### Changing the Number of Dimensions


In [18]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0) # The unsqueeze() method adds a dimension of extent 1. unsqueeze(0) adds it as a new zeroth dimension - now you have a 1x3x226x226 tensor

print(a.shape) # 3x226x226
print(b.shape) # 1x3x226x226

c = torch.rand(1, 1, 1, 1, 1) # 1x1x1x1x1 tensor
print(c) # 1x1x1x1x1 tensor

d = torch.rand(1, 20) # 1x20 tensor
print(d.shape) # 1x20
print(d)

e = d.squeeze(0) # The squeeze() method removes dimensions of extent 1. squeeze(0) removes the zeroth dimension - now you have a 20-element tensor
print(e.shape) # 1 x 20 -> 
print(e)

f = torch.rand(2, 2) # 2x2 tensor
print("f", f.shape) # 2x2
print(f)

g = f.squeeze(0) # 2x2 tensor because there is no dimension of extent 1 to remove
print("g", g.shape)

h = torch.ones(4, 3, 2)

i = h * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to h
print(i)


torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
tensor([[[[[0.9177]]]]])
torch.Size([1, 20])
tensor([[0.1380, 0.0226, 0.3025, 0.1448, 0.5758, 0.8992, 0.2347, 0.1899, 0.4067,
         0.1519, 0.1506, 0.9585, 0.7756, 0.8973, 0.4929, 0.2367, 0.8194, 0.4509,
         0.2690, 0.8381]])
torch.Size([20])
tensor([0.1380, 0.0226, 0.3025, 0.1448, 0.5758, 0.8992, 0.2347, 0.1899, 0.4067,
        0.1519, 0.1506, 0.9585, 0.7756, 0.8973, 0.4929, 0.2367, 0.8194, 0.4509,
        0.2690, 0.8381])
f torch.Size([2, 2])
tensor([[0.8207, 0.6818],
        [0.5057, 0.9335]])
g torch.Size([2, 2])
tensor([[[0.9769, 0.9769],
         [0.2792, 0.2792],
         [0.3277, 0.3277]],

        [[0.9769, 0.9769],
         [0.2792, 0.2792],
         [0.3277, 0.3277]],

        [[0.9769, 0.9769],
         [0.2792, 0.2792],
         [0.3277, 0.3277]],

        [[0.9769, 0.9769],
         [0.2792, 0.2792],
         [0.3277, 0.3277]]])


## The squeeze() and unsqueeze() methods also have in-place versions, squeeze*() and unsqueeze*():


### Radical Reshaping:


In [19]:
output3d = torch.rand(6, 20, 20) # 6x20x20 tensor
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20) # reshapes the tensor to a 1D tensor
print(input1d.shape)

# can also call reshape as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


## NumPy Bridge

### It’s easy to switch between ndarrays and PyTorch tensors:


In [21]:
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array) # convert numpy array to pytorch tensor
print(pytorch_tensor)

pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy() # convert pytorch tensor to numpy array
print(numpy_rand)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.7816, 0.9548, 0.9989],
        [0.4472, 0.8589, 0.0920]])
[[0.78155357 0.954831   0.9988768 ]
 [0.44722855 0.85890746 0.09204096]]


### It is important to know that these converted objects are using the same underlying memory as their source objects, meaning that changes to one are reflected in the other:


In [22]:
numpy_array[1, 1] = 23
print(pytorch_tensor) # pytorch tensor is a view of numpy array, so changing numpy array changes pytorch tensor

pytorch_rand[1, 1] = 17
print(numpy_rand) # numpy array is a view of pytorch tensor, so changing pytorch tensor changes numpy array

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.78155357  0.954831    0.9988768 ]
 [ 0.44722855 17.          0.09204096]]
